// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowIYbgWPJIcoFvU9zSx4xUkaZxC4CDjo',
    appId: '1:624320037059:web:1d6bb17c322c752b8fe276',
    messagingSenderId: '624320037059',
    projectId: 'hello-flutter-cb274',
    authDomain: 'hello-flutter-cb274.firebaseapp.com',
    storageBucket: 'hello-flutter-cb274.appspot.com',
    measurementId: 'G-8T21678GGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTuBc7XCQTdoGYz5RcXIjdfXfFI9CxHs',
    appId: '1:624320037059:android:0826d51764c485148fe276',
    messagingSenderId: '624320037059',
    projectId: 'hello-flutter-cb274',
    storageBucket: 'hello-flutter-cb274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoAOJTlUYiL8jbMRigaWzJVBjlmkLw8s',
    appId: '1:624320037059:ios:b2b74d52e1c5facc8fe276',
    messagingSenderId: '624320037059',
    projectId: 'hello-flutter-cb274',
    storageBucket: 'hello-flutter-cb274.appspot.com',
    iosClientId: '624320037059-astjhcg0s1s894819cv12flutnjms5ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobxEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpoAOJTlUYiL8jbMRigaWzJVBjlmkLw8s',
    appId: '1:624320037059:ios:b2b74d52e1c5facc8fe276',
    messagingSenderId: '624320037059',
    projectId: 'hello-flutter-cb274',
    storageBucket: 'hello-flutter-cb274.appspot.com',
    iosClientId: '624320037059-astjhcg0s1s894819cv12flutnjms5ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobxEx',
  );
}
